version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16 # Use PostgreSQL 16 with pgvector
    container_name: multi_agent_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ai_agent_db} # Use env var or default
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      # No need to explicitly enable pgvector, the image handles it.
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Map host port from .env or default 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local 