"""
Defines the Pydantic models for the input and output of the Reflection/QA Agent.
"""
from pydantic import BaseModel, Field

class QAInput(BaseModel):
    """Input schema for the QA agent, providing the content to be reviewed."""
    content_to_review: str = Field(..., description="The text content generated by another agent that needs quality assurance.")
    original_prompt: str | None = Field(default=None, description="The original user prompt or instruction that led to the content generation (optional).")
    context: str | None = Field(default=None, description="Additional context or knowledge base information used for generation (optional).")

class QAOutput(BaseModel):
    """Output schema for the QA agent, providing feedback and approval status."""
    is_approved: bool = Field(..., description="Whether the content meets the quality standards.")
    feedback: str | None = Field(default=None, description="Constructive feedback or revision suggestions if the content is not approved.") 